# Generated by Django 5.2.6 on 2025-09-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='engine_cc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bike',
            name='kilometers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bike',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bike',
            name='year',
            field=models.IntegerField(),
        ),
    ]
